#!/bin/sh
if [ $# -ne 1 ]
then
	echo "Usage: $0 <path to radix executable>" >&2
	exit 1
fi
radix="$1"

# Usage: RunTest <test name> <source notation> <destination notation> <value> <expected value>
function RunTest()
{
	echo -n "Test \"$1\" ... "
	if [ "$("$radix" "$2" "$3" "$4")" == "$5" ]
	then
		printf "\033[0;32mSucceeded\033[0m\n"
	else
		printf "\033[0;31mFailed\033[0m\n"
		exit 1
	fi
}

RunTest "0" 2 10 0 0
RunTest "-0" 10 2 -0 0
RunTest "MAX_INT" 16 10 7FFFFFFF 2147483647
RunTest "MIN_INT" 16 10 -80000000 -2147483648
RunTest "MAX_INT+1" 16 10 80000000 ""
RunTest "MIN_INT-1" 16 10 -80000001 ""
RunTest "radix < 0" -16 10 CC ""
RunTest "radix < 0" 16 -10 CC ""
RunTest "radix == 0" 16 0 0 ""
RunTest "radix == 1" 16 1 0 ""
RunTest "radix > 36" 37 36 Z ""
RunTest "radix == 36" 36 10 XZ 1223
RunTest "<source notation>-<value> mismatch" 35 10 Z ""
