#!/bin/sh
if [ $# -ne 1 ]
then
	echo "Usage: $0 <path to invert executable>" >&2
	exit 1
fi
tests="$(dirname "$0")/"
invert="$1"

# Usage: RunTest <test name> <test files name>
function RunTest()
{
	echo -n "Test \"$1\" ... "
	if [ "$("$invert" "$tests$2.in")" == "$(cat "$tests$2.out" 2>/dev/null)" ]
	then
		printf "\033[0;32mSucceeded\033[0m\n"
	else
		printf "\033[0;31mFailed\033[0m\n"
		exit 1
	fi
}

RunTest "Unexistent input" unexistent
RunTest "Invertible matrix" invertible
RunTest "Singular matrix" singular
RunTest "Empty input" empty
RunTest "Single line input" single-line
RunTest "Lopsided input" lopsided
RunTest "Oversized input" oversized
RunTest "Garbage in input" garbage
RunTest "Simple matrix" simple
